### ISSUE TITLE
xmltodict module missing

### ISSUE THREAD

**Issue by mmartini-usgs** [dnowacki-usgs/stglib#31]
xmltodict is required when importing stglib.  
(https://github.com/dnowacki-usgs/stglib/blob/master/requirements.txt)

If it isn't in one's environment one gets this error:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-ae9bfbeb1548> in <module>()
     11 import sys
     12 sys.path.append("c:\\projects\\python\\stglib")
---> 13 import xmltodict
     14 import stglib
     15 get_ipython().run_line_magic('matplotlib', 'inline')

ModuleNotFoundError: No module named 'xmltodict'
```

It is not part of the IOOS package (http://ioos.github.io/notebooks_demos/other_resources/)

The work around: 
```
activate IOOS
conda install xmltodict 
```

The permanent solution:
Get xmltodict on the list in ioos.github.io

**Comment by rsignell-usgs** [comment]
I'm not sure this belongs in the IOOS env since this is the first time this has come up, so not a widely used package and not used in the IOOS demos.   Since `xmltodict` is on `conda-forge`, it's easy to add just as you mention.   So I would say it's not a workaround.  It's just a package that some folks might want to add to their IOOS environment (or some other environment).

**Comment by mmartini-usgs** [comment]
OK, so needs to be in the installation instructions for stglib as all it says is:
“If you get errors about missing packages, install them using conda install.”

Or maybe that’s standard practice in python?

Seems to me listing the known non-IOOS packages to expect to install would be helpful since we are going down this path to encourage people to use IOOS and then stglib together.

**Comment by rsignell-usgs** [comment]
How about we maintain our own `environment.yml` for `stglib`?

**Comment by rsignell-usgs** [comment]
This should be easy because we have: 
https://github.com/dnowacki-usgs/stglib/blob/master/requirements.txt

**Comment by mmartini-usgs** [comment]
Yep, and xmltodict is the only thing not in IOOS on that list.  xml is all over the place in raw instrument and other descriptive information.  Seems to me that xmltodict would be a handy addition.

Personally, I'm trying to stay in one python sand box just to keep things simple, efficient and effective.

**Comment by rsignell-usgs** [comment]
I still think it would be best to create your own `environment.yml` for your one python sand box.   Simply take the IOOS env, remove the packages you don't use, and add the ones you do use.   Then when you add new packages, add them to the environment.yml file.   That way when your environment goes belly up (which is bound to happen when you use python) you can easily just create it again.

**Comment by mmartini-usgs** [comment]
Sure I can do that.  

And I stand by my point which I may not have been clear:  to make this package easy to go viral because stglib is intended to be something to help unify data from three Centers.

As someone who has come to python from programming environments that are much more stable, we might find little things like this as headwinds to adoption of stglib more universally.

**Comment by dnowacki-usgs** [comment]
Thanks for your feedback, Marinna. Much appreciated.

An `environment.yml` is one good way to deal with this, and I can add it to my list. I prefer to do as much package management as possible using `conda`, which is why I suggest that unfulfilled dependencies (like `xmltodict`) be taken care of using it. But even better to let people do `conda env create -f environment.yml`  to have their own `stglib` environment.

**Comment by dnowacki-usgs** [comment]
We now have an environment.yml for stglib, closing.
